I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/elizabethquest.rpy", line 61, in script
    show elizabeth tantrum1 in elizabeth_spot
Exception: Image 'elizabeth tantrum1' does not accept attributes 'in elizabeth_spot'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/elizabethquest.rpy", line 61, in script
    show elizabeth tantrum1 in elizabeth_spot
  File "C:\Users\Owner\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Owner\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 1391, in show_imspec
    renpy.config.show(name,
  File "C:\Users\Owner\Desktop\renpy-8.1.3-sdk\renpy\exports.py", line 733, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\Owner\Desktop\renpy-8.1.3-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\Owner\Desktop\renpy-8.1.3-sdk\renpy\display\core.py", line 499, in _duplicate
    args.extraneous()
  File "C:\Users\Owner\Desktop\renpy-8.1.3-sdk\renpy\display\core.py", line 362, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'elizabeth tantrum1' does not accept attributes 'in elizabeth_spot'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
The House On Limbo Lane 1.0
Sun Oct  1 21:02:25 2023
